### ISSUE TITLE
Theme mode (switch) doesn't reset after refresh or Dark theme doesn't set after refresh.

### ISSUE THREAD

**Issue by SarjyantShrestha** [SarjyantShrestha/todo-JS#7]
the dark theme resets but switch doesn't. With this behaviour you can reverse the function of switch which is not ideal.
@uniquesht1 you might want to look at this.

**Comment by uniquesht1** [comment]
@SarjyantShrestha I understand. Sorry for this. Can you assign me this issue ?  
I will make sure to resolve it in the next pull request
